services:
  app:
    image: ghcr.io/1p22geo/wordbook:main
    ports:
      - 0.0.0.0:3000:3000
    networks:
      main:
        ipv4_address: 10.5.0.2
    environment:
      - MONGO_URI=mongodb://10.5.0.3:27017/?directConnection=true
      - OTEL_URI=http://10.5.0.5:4317
  mongodb:
    image: mongo
    networks:
      main:
        ipv4_address: 10.5.0.3
        
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      main:
        ipv4_address: 10.5.0.11

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      main:
        ipv4_address: 10.5.0.12

  # Collector
  otel-collector:
    image: 1p22geo/wordbook-otel
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889"   # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317"   # OTLP gRPC receiver
      - "4318"   # OTLP HTTP receiver
      - "55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    networks:
      main:
        ipv4_address: 10.5.0.5

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
