name: Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint check
        run: yarn lint
      - name: Format check
        run: yarn prettier
      - name: Unit & Integration tests
        run: yarn coverage
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/
          retention-days: 30
