name: Auto Merge Dependabot
on: [pull_request]
jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          pullRequestOpened: |
            @dependabot merge